repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.83.5
    hooks:
      - id: terraform_fmt
      #- id: terraform_docs
      #   args:
      #     - --hook-config=--path-to-file=README.md        # Valid UNIX path. I.e. ../TFDOC.md or docs/README.md etc.
      #     - --hook-config=--add-to-existing-file=true     # Boolean. true or false
      #     - --hook-config=--create-file-if-not-exist=true # Boolean. true or false
      - id: terraform_tflint
        exclude: "test/"
        args:
          - --args=--config=__GIT_WORKING_DIR__/.tflint.hcl
      # - id: terraform_validate
      # - id: checkov
      # - id: terraform_tfsec
      # - id: terrascan
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=500']
      - id: pretty-format-json
        args: ['--autofix', '--no-sort-keys', '--indent=2']
      - id: check-byte-order-marker
      - id: check-case-conflict
      #- id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-symlinks
      - id: detect-private-key
      - id: check-merge-conflict
      - id: detect-aws-credentials
        args: ['--allow-missing-credentials']
      - id: trailing-whitespace